---
abstract:
all_day: false
authors: [admin, "Louis Rocconi"]
date: "2021-08-11T1:00:00Z"
date_end: "2021-08-11T3:00:00Z"
event: 2021 Joint Statistical Meeting
event_url: https://web.archive.org/web/20210716145020/https://ww2.amstat.org/meetings/jsm/2021/onlineprogram/AbstractDetails.cfm?abstractid=317897
featured: false
image:
  focal_point: Right
location: 
math: true
projects:
publishDate: "2021-07-15T00:00:00Z"
slides: 
summary: "This presentation will discuss the switch from SPSS to R in an advanced graduate-level applied statistics course in an educational psychology program."
tags: [Data Science]
title: "From Click to Code: Insights from Instructors and Students on Moving from SPSS to R in a Graduate-Level Applied Statistics Course"
url_code: ""
url_pdf: ""
url_slides: "https://docs.google.com/presentation/d/1q5XOeduoXbsHOEC1uN6_IQNbVw8-ActazPkXBlu633g/edit?usp=sharing"
url_video: ""
output:
  md_document
---


- Classroom Teaching and Pedagogy — Contributed Speed Session
- Section on Statistics and Data Science Education, Section on Teaching of Statistics in the Health Sciences, Text Analysis Interest Group
- Chair(s): Jamis Perrett, Bayer U.S.

## Abstract

Proprietary software such as SPSS, Stata, and SAS have traditionally dominated statistics courses, particularly in applied statistics courses in the social and behavioral sciences. More recently, R has become the software package of choice due to its open-source nature, limited resource use, and flexibility. While these features may excite veteran researchers and statisticians, the R programming language can feel daunting to students, especially those who have become accustomed to point-and-click software and graphical user interfaces. This presentation will discuss the switch from SPSS to R in an advanced graduate-level applied statistics course in an educational psychology program. The presentation will focus on strategies implemented by the instructors for designing materials, scaffolding, and developing practice activities and assessments. In addition, results from a survey on students’ experiences, challenges, and strategies with transitioning to and learning R will be shared. Insights for module sequencing, material design, and general pedagogy will be highlighted.

## Resources 

- Interactive R Reference Guide
  - [.Rmd file used to create guide](https://github.com/acircleda/blog/blob/master/content/talk/2021-8-fromclicktocode/Data-Analysis-with-R.Rmd)
  - [.html file given to students](https://github.com/acircleda/blog/blob/master/content/talk/2021-8-fromclicktocode/Data-Analysis-with-R.html)
- [Heloful R Code (.pdf)](Helpful-R-Code.pdf)